#!/bin/sh
set -eu

node <<'EOF'
const fs = require('fs')
const path = require('path')

const root = process.cwd()
const catalogPath = path.join(root, 'catalog', 'skills.json')
const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'))
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
const projectName = catalog.name
const claudeMarketplaceName = 'olko-agent-skills'
const lookupNameFor = (pkg) => pkg.lookupName || pkg.name
const skillPathFor = (pkg) => path.join(root, pkg.path, 'SKILL.md')
const promptNameFor = (pkg) => `${pkg.name}.prompt.md`
const generatedHeader = '<!-- Generated by scripts/build-adapters.sh. Do not edit directly. -->'
const stripFrontmatter = (content) => content.replace(/^---\n[\s\S]*?\n---\n?/, '')
const stripTrailingLineWhitespace = (content) => content.replace(/[ \t]+$/gm, '')

const claudeSkillPaths = catalog.packages
  .filter((pkg) => pkg.adapters.includes('claude'))
  .map((pkg) => `./${pkg.path}`)

const plugins = [
  {
    name: claudeMarketplaceName,
    source: './',
    description: 'Agent-agnostic skill catalog for Codex, Claude, Cursor, and other skill-aware tools.',
  },
]

const cursorPlugins = catalog.packages.map((pkg) => ({
  name: lookupNameFor(pkg),
  source: `./${pkg.path}/adapters/cursor`,
  description: pkg.description,
}))

fs.mkdirSync(path.join(root, '.claude-plugin'), { recursive: true })
fs.mkdirSync(path.join(root, '.cursor-plugin'), { recursive: true })
fs.mkdirSync(path.join(root, '.github', 'prompts'), { recursive: true })

fs.writeFileSync(
  path.join(root, '.claude-plugin', 'marketplace.json'),
  JSON.stringify(
    {
      name: claudeMarketplaceName,
      owner: { name: 'Oleg Koval' },
      metadata: {
        description: 'Agent-agnostic skill catalog for Codex, Claude, Cursor, and other skill-aware tools.',
      },
      plugins,
    },
    null,
    2,
  ) + '\n',
)

fs.writeFileSync(
  path.join(root, '.cursor-plugin', 'index.json'),
  JSON.stringify(
    {
      name: projectName,
      plugins: cursorPlugins,
    },
    null,
    2,
  ) + '\n',
)

fs.writeFileSync(
  path.join(root, '.claude-plugin', 'plugin.json'),
  JSON.stringify(
    {
      name: claudeMarketplaceName,
      description: 'Agent-agnostic skill catalog for Codex, Claude, Cursor, and other skill-aware tools.',
      version: packageJson.version,
      author: { name: 'Oleg Koval' },
      homepage: 'https://github.com/oleg-koval/agent-skills',
      repository: 'https://github.com/oleg-koval/agent-skills',
      license: 'MIT',
      skills: claudeSkillPaths,
    },
    null,
    2,
  ) + '\n',
)

const copilotInstructions = [
  generatedHeader,
  '',
  '# Agent Skills Repository Instructions',
  '',
  'This repository is an opinionated agent skill catalog. Skills encode concrete defaults, preferred tools, and repeatable workflows.',
  '',
  '- Treat `catalog/skills.json` as the source of truth for package metadata.',
  '- Keep canonical skill instructions in `packages/{category}/{skill}/SKILL.md`.',
  '- Keep generated adapter files in sync by running `./scripts/build-adapters.sh` after catalog or skill metadata changes (includes Cursor `skills/*/SKILL.md` copies from each canonical `SKILL.md`).',
  '- Run `./scripts/validate-catalog.sh` before release.',
  '- Prefer small, scoped updates that preserve existing package structure.',
  '',
  'Available reusable prompt files:',
  ...catalog.packages.map((pkg) => `- ${pkg.name}: .github/prompts/${promptNameFor(pkg)}`),
  '',
].join('\n')

fs.writeFileSync(path.join(root, '.github', 'copilot-instructions.md'), copilotInstructions)

for (const pkg of catalog.packages) {
  if (!pkg.adapters.includes('copilot')) {
    continue
  }

  const skillBody = stripFrontmatter(fs.readFileSync(skillPathFor(pkg), 'utf8')).trimEnd()
  const prompt = stripTrailingLineWhitespace([
    generatedHeader,
    '',
    '---',
    `description: ${JSON.stringify(pkg.description)}`,
    '---',
    '',
    `Use the ${lookupNameFor(pkg)} skill.`,
    '',
    skillBody,
    '',
  ].join('\n'))

  fs.writeFileSync(path.join(root, '.github', 'prompts', promptNameFor(pkg)), prompt)
}

for (const pkg of catalog.packages) {
  const canonical = fs.readFileSync(skillPathFor(pkg), 'utf8').trimEnd()

  if (pkg.adapters.includes('claude')) {
    const claudeDestDir = path.join(root, pkg.path, 'adapters', 'claude', 'skills', pkg.name)
    fs.mkdirSync(claudeDestDir, { recursive: true })
    fs.writeFileSync(
      path.join(root, pkg.path, 'adapters', 'claude', 'plugin.json'),
      JSON.stringify(
        {
          name: `olko-${pkg.name}`,
          description: pkg.description,
          skills: './skills',
        },
        null,
        2,
      ) + '\n',
    )
    fs.writeFileSync(path.join(claudeDestDir, 'SKILL.md'), [generatedHeader, '', canonical, ''].join('\n'))
  }

  if (!pkg.adapters.includes('cursor')) {
    continue
  }

  const destDir = path.join(root, pkg.path, 'adapters', 'cursor', 'skills', pkg.name)
  const destPath = path.join(destDir, 'SKILL.md')
  fs.mkdirSync(destDir, { recursive: true })
  fs.writeFileSync(destPath, [generatedHeader, '', canonical, ''].join('\n'))
}

console.log('generated marketplace manifests, Copilot prompts, and Cursor adapter SKILL.md files')
EOF
