#!/bin/sh
set -eu

node --input-type=module <<'EOF'
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, cpSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { loadCatalog } from './scripts/lib/catalog.mjs'

const root = process.cwd()
const catalog = loadCatalog()
const packageJson = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const MARKETPLACE = 'olko-agent-skills'
const DESCRIPTION = 'Agent-agnostic skill catalog for Codex, Claude, Cursor, Grok, Copilot, Windsurf, Kiro, and other skill-aware tools.'
const generatedHeader = '<!-- Generated by scripts/build-adapters.sh. Do not edit directly. -->'

const lookupNameFor = (skill) => skill.lookupName || skill.name
const skillFile = (skill) => join(root, skill.path, 'SKILL.md')
const stripFrontmatter = (c) => c.replace(/^---\n[\s\S]*?\n---\n?/, '')
const extractFrontmatter = (c) => {
  const m = c.match(/^(---\n[\s\S]*?\n---\n?)/)
  if (!m) return ''
  return m[1].endsWith('\n') ? m[1] : m[1] + '\n'
}
const stripTrailing = (c) => c.replace(/[ \t]+$/gm, '')
const writeJson = (p, value) => {
  mkdirSync(dirname(p), { recursive: true })
  writeFileSync(p, JSON.stringify(value, null, 2) + '\n')
}
const copyResources = (skill, destDir) => {
  for (const d of ['scripts', 'references', 'templates']) {
    const src = join(root, skill.path, d)
    if (!existsSync(src)) continue
    const dest = join(destDir, d)
    rmSync(dest, { recursive: true, force: true })
    cpSync(src, dest, { recursive: true })
  }
}
const wrap = (frontmatter, body) => [frontmatter + generatedHeader, '', body, ''].join('\n')
const ruleFile = (description, body, extraFrontmatter = []) => stripTrailing([
  generatedHeader, '', '---',
  ...extraFrontmatter,
  `description: ${JSON.stringify(description)}`,
  '---', '', body, '',
].join('\n'))

// --- per-plugin Claude manifests -------------------------------------------
for (const plugin of catalog.plugins) {
  writeJson(join(root, 'plugins', plugin.name, '.claude-plugin', 'plugin.json'), {
    name: plugin.name,
    description: plugin.description,
    version: packageJson.version,
    author: { name: 'Oleg Koval' },
    homepage: 'https://github.com/oleg-koval/agent-skills',
    repository: 'https://github.com/oleg-koval/agent-skills',
    license: 'MIT',
    skills: './skills',
    ...(plugin.userConfig ? { userConfig: plugin.userConfig } : {}),
  })
}

// --- marketplace ------------------------------------------------------------
writeJson(join(root, '.claude-plugin', 'marketplace.json'), {
  name: MARKETPLACE,
  owner: { name: 'Oleg Koval' },
  metadata: { description: DESCRIPTION },
  plugins: catalog.plugins.map((p) => ({
    name: p.name,
    source: `./plugins/${p.name}`,
    description: p.description,
  })),
})

// --- cursor and grok indexes, keyed by plugin -------------------------------
const pluginsWith = (target) => catalog.plugins
  .filter((p) => p.skills.some((s) => s.adapters.includes(target)))
  .map((p) => ({ name: p.name, source: `./adapters/${target}/${p.name}`, description: p.description }))

writeJson(join(root, '.cursor-plugin', 'index.json'), { name: catalog.name, plugins: pluginsWith('cursor') })
writeJson(join(root, '.grok-plugin', 'index.json'), { name: catalog.name, plugins: pluginsWith('grok') })

// --- copilot instructions ---------------------------------------------------
writeFileSync(join(root, '.github', 'copilot-instructions.md'), [
  generatedHeader, '',
  '# Agent Skills Repository Instructions', '',
  'This repository is an opinionated agent skill catalog. Skills encode concrete defaults, preferred tools, and repeatable workflows.', '',
  '- Treat `catalog/skills.json` as the source of truth for plugin and skill metadata.',
  '- Keep canonical skill instructions in `plugins/{plugin}/skills/{skill}/SKILL.md`.',
  '- Regenerate every manifest and adapter with `./scripts/build-adapters.sh` after any catalog or skill metadata change.',
  '- Run `./scripts/validate-catalog.sh` before release.',
  '- Never edit a generated file directly.', '',
  'Available reusable prompt files:',
  ...catalog.skills.filter((s) => s.adapters.includes('copilot'))
    .map((s) => `- ${s.name}: .github/prompts/${s.name}.prompt.md`),
  '',
].join('\n'))

// --- per-skill targets ------------------------------------------------------
mkdirSync(join(root, '.github', 'prompts'), { recursive: true })
mkdirSync(join(root, '.windsurf', 'rules'), { recursive: true })
mkdirSync(join(root, '.kiro', 'steering'), { recursive: true })

for (const skill of catalog.skills) {
  const canonical = readFileSync(skillFile(skill), 'utf8').trimEnd()
  const fm = extractFrontmatter(canonical)
  if (!fm) throw new Error(`canonical SKILL.md has no frontmatter: ${skillFile(skill)}`)
  const body = stripTrailing(stripFrontmatter(canonical).trimStart().trimEnd())

  if (skill.adapters.includes('copilot')) {
    writeFileSync(join(root, '.github', 'prompts', `${skill.name}.prompt.md`),
      ruleFile(skill.description, `Use the ${lookupNameFor(skill)} skill.\n\n${body}`))
  }
  if (skill.adapters.includes('windsurf')) {
    writeFileSync(join(root, '.windsurf', 'rules', `${skill.name}.md`),
      ruleFile(skill.description, body))
  }
  if (skill.adapters.includes('kiro')) {
    writeFileSync(join(root, '.kiro', 'steering', `${skill.name}.md`),
      ruleFile(skill.description, body, ['inclusion: manual']))
  }

  for (const target of ['claude', 'cursor', 'grok']) {
    if (!skill.adapters.includes(target)) continue
    const destDir = join(root, 'adapters', target, skill.plugin.name, 'skills', skill.name)
    mkdirSync(destDir, { recursive: true })
    writeFileSync(join(destDir, 'SKILL.md'), wrap(fm, body))
    copyResources(skill, destDir)
  }
  // codex, pi and hermes are pointer adapters: one README per plugin listing the
  // canonical skills, rather than a copy of each SKILL.md.
  for (const target of ['codex', 'pi', 'hermes']) {
    if (!skill.adapters.includes(target)) continue
    const label = { codex: 'Codex', pi: 'Pi', hermes: 'Hermes' }[target]
    const dir = join(root, 'adapters', target, skill.plugin.name)
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, 'README.md'), [
      generatedHeader, '', `# ${label} adapter: ${skill.plugin.name}`, '',
      'Use the canonical skills directly:', '',
      ...skill.plugin.skills.filter((s) => s.adapters.includes(target))
        .map((s) => `- \`${s.path}/SKILL.md\``),
      '',
    ].join('\n'))
  }
}

// --- per-plugin adapter manifests -------------------------------------------
for (const plugin of catalog.plugins) {
  for (const target of ['claude', 'cursor', 'grok']) {
    if (!plugin.skills.some((s) => s.adapters.includes(target))) continue
    const dir = join(root, 'adapters', target, plugin.name)
    const manifest = target === 'claude'
      ? { name: plugin.name, description: plugin.description, skills: './skills' }
      : { name: plugin.name, version: '0.1.0', description: plugin.description, skills: 'skills/' }
    writeJson(join(dir, 'plugin.json'), manifest)
  }
}

console.log(`generated ${catalog.plugins.length} plugin manifests and 7 adapter targets for ${catalog.skills.length} skills`)
EOF
